import Head from 'next/head'
import { Inter } from 'next/font/google'
import Header from '@/components/Header'
import Hero from '@/components/Hero'
import About from '@/components/About'
import Skills from '@/components/Skills'

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  return (
    <div className='bg-sky-400 h-screen snap-y snap-mandatory overflow-scroll z-0 text-white'>
      <Head>
        <title>Juan's Portfolio</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      
      <Header />

      <section id='hero' className='snap-center'>
        <Hero/>
      </section>

      <section id='about' className='snap-center'>
        <About/>
      </section>

      {/* Skills */}
      <section id='skills' className='snap-center'>
        <Skills/>
      </section>
      {/* Projects */}
      {/* Contact Me */}

    </div>
  )
}
